In [1]:
import numpy as np
import pandas as pd
import sympy as sp

In [2]:
def f(arr):
    return np.array( [int(arr[i] == 1) for i in range(arr.shape[0])] )

def int_to_state(x_int, N):
    return np.array([int(ch) for ch in bin(x_int)[2:].rjust(N, "0")])

def state_to_int(x_arr, N):
    return int( "".join([str(x_arr[_]) for _ in range(N)] ), 2)

In [12]:
# I want to write an algorithm to calculate the transition matrix 
N = 3
adj = np.random.choice([0,1], size=N**2).reshape((N,N))
adj

array([[1, 0, 1],
       [0, 0, 0],
       [0, 0, 1]])

In [13]:
num_states = 2**N


array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
p = 0.005

In [35]:
# We'll use convention from col to row
trans = np.zeros((num_states,num_states))

# We're gonna iterate over the states
for x_int in range(num_states):
    # Get the state corresponding to the number
    x_arr = int_to_state(x_int, N)

    # Now, we're gonna iterate over the injections
    for b_int in range(num_states):
        b_arr = int_to_state(b_int, N)

        # Find out how many injections came with this b
        num_inj = np.sum(b_arr)

        # Get the probability of this injection vector
        prob = p**num_inj * (1-p)**(N-num_inj)

        # Calculate the output of the function
        w_arr = f( np.matmul(adj,x_arr) + b_arr )
        
        # Get the integer corresponding to the output
        w_int = state_to_int(w_arr, N)

        # Update the transition matrix
        trans[w_int, x_int] += prob



In [36]:
trans

array([[9.85074875e-01, 2.48750000e-05, 9.85074875e-01, 2.48750000e-05,
        4.95012500e-03, 4.97500000e-03, 4.95012500e-03, 4.97500000e-03],
       [4.95012500e-03, 4.95012500e-03, 4.95012500e-03, 4.95012500e-03,
        2.48750000e-05, 9.90025000e-01, 2.48750000e-05, 9.90025000e-01],
       [4.95012500e-03, 1.25000000e-07, 4.95012500e-03, 1.25000000e-07,
        2.48750000e-05, 2.50000000e-05, 2.48750000e-05, 2.50000000e-05],
       [2.48750000e-05, 2.48750000e-05, 2.48750000e-05, 2.48750000e-05,
        1.25000000e-07, 4.97500000e-03, 1.25000000e-07, 4.97500000e-03],
       [4.95012500e-03, 4.95012500e-03, 4.95012500e-03, 4.95012500e-03,
        9.85074875e-01, 0.00000000e+00, 9.85074875e-01, 0.00000000e+00],
       [2.48750000e-05, 9.85074875e-01, 2.48750000e-05, 9.85074875e-01,
        4.95012500e-03, 0.00000000e+00, 4.95012500e-03, 0.00000000e+00],
       [2.48750000e-05, 2.48750000e-05, 2.48750000e-05, 2.48750000e-05,
        4.95012500e-03, 0.00000000e+00, 4.95012500e-03, 0.

In [38]:
np.sum(trans, axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
eigen = np.linalg.eig(trans)

In [46]:
eigen

(array([-9.90012531e-01,  5.63785130e-18,  1.00000000e+00,  9.85037531e-01,
         9.90000000e-01, -7.08890839e-18, -1.70221699e-18,  8.53584731e-19]),
 array([[-1.78110850e-03,  7.07106781e-01,  5.00412619e-01,
         -7.07095633e-01,  4.98732675e-01, -1.38172890e-01,
          6.73135176e-01,  1.58833859e-01],
        [-7.07095610e-01, -1.34785983e-15,  5.01243827e-01,
         -1.77215826e-03, -5.01251527e-01,  6.83876199e-01,
         -5.55778950e-02, -4.04575991e-01],
        [-8.95029397e-06, -7.07106781e-01,  2.51463627e-03,
         -3.55324439e-03,  2.50619435e-03,  1.38172890e-01,
         -6.73135176e-01, -1.58833859e-01],
        [-3.55324427e-03, -4.57449925e-18,  2.51881320e-03,
         -8.90531790e-06, -2.51885189e-03, -6.83876199e-01,
          5.55778950e-02,  4.04575991e-01],
        [ 1.78110850e-03, -1.49611750e-16,  4.99573014e-01,
          7.07095633e-01,  5.01251527e-01,  4.32247500e-02,
         -2.47951938e-02, -5.57650612e-01],
        [ 7.07095610e-01, 

In [61]:
M = np.max(eigen[0])

idx = list(eigen[0]).index(M)

stat_dsbn = eigen[1][:,idx]
stat_dsbn

array([0.50041262, 0.50124383, 0.00251464, 0.00251881, 0.49957301,
       0.49874181, 0.00251042, 0.00250624])

In [62]:
sum(stat_dsbn)
# God dammit that's not right!

2.01002137288548