In [1]:
import pandas as pd
import numpy as np

In [2]:
# Target number of nodes
N = 10

In [61]:
a = 0.125
b = 0.75
c = 1 - b - a

d_in = 1
d_out = 1

In [198]:
# Initialize the adjacency matrix
adj = np.zeros((N+1,N+1))
# MAKE SURE TO TAKE THE APPROPRIATE SLICE WHEN YOU PULL OUT
# THE ADJACENCY MATRIX

# Current number of nodes
n = 1

# Make a random choice between having a lone node or a node with a loop
adj[0,0] = np.random.choice(a=[0,1], size=1)

# Set the time to the number of edges
t = int(np.sum(np.sum(adj)))

# Initialize the edge choice distributions
p_out = (np.sum(adj[0:n,0:n], axis=0) + d_out) / (t + d_out*n)
p_in  = (np.sum(adj[0:n,0:n], axis=1) + d_in ) / (t + d_in *n)

while n <= N:
    # Increment time; you'll add an edge no matter what
    t += 1

    # Make a choice and add an edge appropriately
    choice = np.random.choice(a=[0,1,2], size=1, p=[a,b,c])[0]
    if choice == 0:
        j = n
        i = np.random.choice(a=list(range(len(p_in))), size=1, p=p_in)[0]
    elif choice == 1:
        j = np.random.choice(a=list(range(len(p_out))), size=1, p=p_out)[0]
        i = np.random.choice(a=list(range(len(p_in))), size=1, p=p_in)[0]
    else:
        j = np.random.choice(a=list(range(len(p_out))), size=1, p=p_out)[0]
        i = n
    adj[i,j] += 1

    # Increment number of nodes
    if choice != 1:
        n += 1

    # Increment probability distributions
    p_out = (np.sum(adj[0:n,0:n], axis=0) + d_out) / (t + d_out*n)
    p_in  = (np.sum(adj[0:n,0:n], axis=1) + d_in ) / (t + d_in *n)

adj = np.array(adj[0:N, 0:N] > 0, dtype=int)

[[1 1 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 1 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [1 0 0 1 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]]
[4 7 3 1 1 1 0 1 0 0]
[2 3 2 2 2 1 3 1 1 1]


In [219]:
# Simple directed stochastic block model (all blocks are same size)
communities = 3
num_blocks = communities**2
blocks = np.random.random(size = num_blocks).reshape((communities, communities))

# Number of nodes
N = 10
adj = np.zeros((N,N))

# Randomly place these nodes in communities
# Sorting changes nothing, and hopefully makes the adjacency matrix better
# resemble the graphon if you were to take the correct average on 
# adjacency matrices with large N
comm = np.sort(np.random.choice(a=range(communities), size=N, replace=True))

# Place directed edges according to the blocks
for j in range(N):
    for i in range(N):
        prob = blocks[comm[i],comm[j]]
        adj[i,j] = np.random.choice(a=[0,1], size=1, p=[1-prob, prob])

In [220]:
adj

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 1., 1., 1., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 1., 1., 1.],
       [1., 0., 1., 1., 0., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 0., 1., 1., 1., 1., 0.],
       [0., 0., 1., 0., 0., 1., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 1.]])

In [232]:
# A "bounded plane" digraphon
W1 = np.array([0.5,0.5,0.5])
W2 = np.array([1,  0.5,0])
W3 = np.array([1, 1, 0.5])

def get_plane(W1, W2, W3):
    u1 = W1[0]; v1 = W1[1]; w1 = W1[2]
    u2 = W2[0]; v2 = W2[1]; w2 = W2[2]
    u3 = W3[0]; v3 = W3[1]; w3 = W3[2]
    def plane(u,v):
        const = u1*(v2*w3-v3*w2) + v1*(u3*w2-u2*w3) + w1*(u2*v3-u3*v2)
        v_part = -(u3*w2-u2*w3)*v
        u_part = -(v2*w3-v3*w2)*u
        return (const+v_part+u_part)/(u2*v3-u3*v2)
    return plane
        

In [233]:
plane = get_plane(W1,W2,W3)

In [234]:
plane(0.5,0.5)

0.5

In [235]:
plane(1, 0.5)
# Darn it, this is wrong. Try again sometime soon.

0.25

In [236]:
plane(1,1)

0.75