In [1]:
import numpy as np

In [2]:
seed_graph = np.array([[1,2],[3,4]])

In [7]:
def directed_scale_free(n):
    adjacency_matrix = np.zeros((n,n))
    adjacency_matrix[0,1] += 1
    adjacency_matrix[1,0] += 1

    t = 2

    for i in range(2):
        for j in range(2):
            if i != j:
                edge_increment = np.random.choice([0,1])
                adjacency_matrix[i,j] += edge_increment
                t += edge_increment


    # Initialize various parameters
    n_current = 2
    prob_a = 0.25
    prob_b = 0.5
    prob_c = 0.25
    delta_in = 0.6666666666666667
    delta_out = 0.6666666666666667

    
    in_numerators = np.sum(adjacency_matrix, axis=1) + delta_in
    in_denominator = t + delta_in*n_current
    out_numerators = np.sum(adjacency_matrix, axis=0) + delta_out
    out_denominator = t + delta_out*n_current

    while n_current <= n:
        # Choose action
        action = np.random.choice(["A", "B", "C"], p=[prob_a, prob_b, prob_c])
        
        try:
            if action == "A":
                pass
            elif action == "B":
                pass
            else:
                pass

            # Update the in_numerators, etc

        except IndexError:
            break

    


array([[0, 1],
       [1, 0]])

In [5]:
seed_graph[1,1] += 4

In [12]:
np.sum(seed_graph, axis=0)

array([ 4, 10])

In [6]:
seed_graph

array([[1, 2],
       [3, 8]])

In [10]:
2/3

0.6666666666666666

In [16]:
np.random.choice(["A", "B"])

'B'