In [3]:
import numpy as np

The function in the next cell comes from the paper "Directed Scale Free Graphs" by Bollobas, Borgs, Chayes, and Riordan. The graph model in that paper takes 5 parameters: $\alpha$, $\beta$, $\gamma$, $\delta_{in}$, and $\delta_{out}.$ It is stipulated that all of these parameters are non-negative, and that $\alpha + \beta + \gamma = 1$.

In what follows, I have set $\alpha = \frac{1}{4}$, $\beta = \frac{1}{2}$, and $\gamma = \frac{1}{4}$. I chose these values because they are the most symmetric choice for these parameters that does not lead to a trivial network. 

Now, the paper gives an equation in terms of these five parameters for the expected exponent in the power law distribution. Since scale free graphs techincally a power law degree distribution with the exponent strictly between 2 and 3, I set the desired exponent for both degree distribution equal to 2.5. Then, we can solve for the other two parameters, obtaining $\delta_{in} = \frac{2}{3}$ and $\delta_{out} = \frac{2}{3}$.

In [88]:
def directed_scale_free(n):
    adjacency_matrix = np.zeros((n,n))
    adjacency_matrix[0,1] += 1
    adjacency_matrix[1,0] += 1

    t = 2

    for i in range(2):
        for j in range(2):
            if i != j:
                edge_increment = np.random.choice([0,1])
                adjacency_matrix[i,j] += edge_increment
                t += edge_increment


    # Initialize various parameters
    n_current = 2
    prob_a = 0.25
    prob_b = 0.5
    prob_c = 0.25
    delta_in = 0.6666666666666667
    delta_out = 0.6666666666666667

    nodes = np.array(range(n))

    # These values are related to choosing nodes according to the various actions. We don't want to add deltas to nodes with no edges, so we multiply them by the indicators below
    in_numerators = np.sum(adjacency_matrix, axis=1) + delta_in*( np.sum(adjacency_matrix, axis=1) > 0 )
    in_denominator = t + delta_in*n_current
    out_numerators = np.sum(adjacency_matrix, axis=0) + delta_out*( np.sum(adjacency_matrix, axis=0) > 0 )
    out_denominator = t + delta_out*n_current

    in_distribution = in_numerators / in_denominator
    out_distribution = out_numerators / out_denominator

    while n_current < n:
        # Choose action
        action = np.random.choice(["A", "B", "C"], p=[prob_a, prob_b, prob_c])

        print("t = " + str(t))
        print(adjacency_matrix)
        print("action = " + action)
        print("out_distribution = " + str(out_distribution))
        print("in_distribution = " + str(in_distribution))
        print("sum of out_distribution = " + str(np.sum(out_distribution)) + ", sum of in_distribution = " + str(np.sum(in_distribution)))
        
        try:
            if action == "A":
                j = n_current
                i = np.random.choice(nodes, p=in_distribution)
                #out_numerators[j] += 1 + delta_out
                #in_numerators[i] += 1
                n_current += 1
            elif action == "B":
                j = np.random.choice(nodes, p=out_distribution)
                i = np.random.choice(nodes, p=in_distribution)
                #out_numerators[j] += 1
                #in_numerators[i] += 1
            else:
                j = np.random.choice(nodes, p=out_distribution)
                i = n_current
                #out_numerators[j] += 1
                #in_numerators[i] += 1 + delta_in
                n_current += 1
            t += 1
            #adjacency_matrix[i,j] += 1
            #t += 1
            #in_denominator = t + delta_in*n_current
            #out_denominator = t + delta_out*n_current
            #in_distribution = in_numerators / in_denominator
            #out_distribution = out_numerators / out_denominator4

            in_numerators = np.sum(adjacency_matrix, axis=1) + delta_in*( np.sum(adjacency_matrix, axis=1) > 0 )
            in_denominator = t + delta_in*n_current
            out_numerators = np.sum(adjacency_matrix, axis=0) + delta_out*( np.sum(adjacency_matrix, axis=0) > 0 )
            out_denominator = t + delta_out*n_current
            in_distribution = in_numerators / in_denominator
            out_distribution = out_numerators / out_denominator
            
        except IndexError:
            break
    return adjacency_matrix

    


In [89]:
directed_scale_free(5)

t = 3
[[0. 1. 0. 0. 0.]
 [2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
action = B
out_distribution = [0.61538462 0.38461538 0.         0.         0.        ]
in_distribution = [0.38461538 0.61538462 0.         0.         0.        ]
sum of out_distribution = 1.0, sum of in_distribution = 1.0
t = 4
[[0. 1. 0. 0. 0.]
 [2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
action = B
out_distribution = [0.5    0.3125 0.     0.     0.    ]
in_distribution = [0.3125 0.5    0.     0.     0.    ]
sum of out_distribution = 0.8125, sum of in_distribution = 0.8125


ValueError: probabilities do not sum to 1

In [72]:
5 - True

4